server:
  port: 8082

spring:
  application:
    name: messages-service
  kafka:
    topic: messages
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ua.kpi.sharedmodel
      group-id: messages-group-id1
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        serviceName: ${spring.application.name}

  config:
    import: "optional:consul:"


management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
