server:
  port: 8081

spring:
  application:
    name: logging-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        serviceName: ${spring.application.name}
  config:
    import: "optional:consul:"

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

