server:
  port: 8080


spring:
  application:
    name: facade-service
  kafka:
    topic: messages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        instance-id: ${spring.application.name}-${server.port}
        serviceName: ${spring.application.name}
  config:
    import: "optional:consul:"


external:
  service:
    logging:
      name: logging-service
    messages:
      name: messages-service



management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

